server:
  port: 9090

spring:
  zipkin:
    enabled: true
    base-url: http://localhost:9411
    service:
      name: auth-service
  security:
    user:
      name: aral
      password: root
  rabbitmq:
    host: localhost
    port: 5672
    username: aral
    password: root
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:9999/TemporaryAuthDB
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true