server:
  port: 9094

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: aral
    password: root
#  mail:
#    host: smtp.gmail.com
#    port: 587
#    username:
#    password:
#    properties:
#      mail:
#        smtp:
#          auth: true
#          starttls:
#            enable: true