server:
  port: 9091

spring:
  zipkin:
    enabled: true
    base-url: http://localhost:9411
    service:
      name: userprofile-service
  rabbitmq:
    host: localhost
    port: 5672
    username: aral
    password: root
  data:
    mongodb:
      host: localhost
      port: 27000
      database: TemporaryUserProfileDB
      username: AralMongoDB
      password: Aral12345